spring:
  application:
    name: library-management-system

  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:librarydb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    username: test@123
    password: test@123
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: test@123
      password: password@123
